### ISSUE TITLE
Error: expected authentication challenge, but no secret was required

### ISSUE THREAD

**Issue by makis10** [ekzhang/bore#100]
Hello, im trying to host my own bore server in an EC2. i have set a secret for my server and i have an nginx running on port 80 on the ec2. I have all the traffic allowed from my ip to/from the ec2.

from my pc im trying to connect with `bore local --to my.bore.server --secret $BORE_SECRET 8000` and i get the error on the title...what does it mean?

if i dont set the `secret` i get "Error: unexpected EOF"

**Comment by ekzhang** [comment]
How are you using Nginx, and why do you need to use it?

**Comment by ekzhang** [comment]
I can't help you unless you provide more details. Bore is a service on Layer 4, TCP.

Perhaps read more about networking first?
