### ISSUE TITLE
What's the shell you use in README?

### ISSUE THREAD

**Issue by tdzz1102** [ekzhang/bore#101]
Sorry for the unrelated issue but it was really cool to get hint like copilot when typing shell command!

![](https://camo.githubusercontent.com/895c0a44b8f14a929f4efbeda90eeb4149610a901f85ef03f50a3cbfacabbb76/68747470733a2f2f692e696d6775722e636f6d2f76446547736d782e676966)

**Comment by ekzhang** [comment]
Haha no worries! It's zsh with https://github.com/zsh-users/zsh-autosuggestions
