### ISSUE TITLE
How closed specific port without close alls, or restart bore?

### ISSUE THREAD

**Issue by belimpur** [ekzhang/bore#103]
How do I release a specific port on the bore server, without having to close them all or restart bore? 

That is, being able to close the connection to a specific port in use without having to interrupt the others.

**Comment by ekzhang** [comment]
You can stop the `bore` client process

**Comment by belimpur** [comment]
Yes, that is correct.
But the problem that occurs is that even after doing that, on the server, several minutes later, the port is still busy.
If you try to reconnect the client to the same port, the port remains busy for several minutes.
The question is: how to force the port to be closed and unlocked from the server?

**Comment by belimpur** [comment]
Yes, that is correct.

But the problem that occurs is that even after doing that, on the server, several minutes later, the port is still busy.

If you try to reconnect the client to the same port, the port remains busy for several minutes.

The question is: how to force the port to be closed and unlocked from the server?

**Comment by belimpur** [comment]
And when you try to connect again on the same port on the server side:

bore local 80 --to my.server --port 9500
Error: server error: port already in use

**Comment by anthonyhayesres** [comment]
Seeing the same issue as belimpur here, it'd be great to have a `--force` flag to avoid that `Error: server error: port already in use`
