### ISSUE TITLE
Connection refused (os error 111) when running `bore local`

### ISSUE THREAD

**Issue by ThatOneCalculator** [ekzhang/bore#104]
I'm having this problem persistently, even after reboots

```
bore local --to bore.pub 3001
Error: could not connect to bore.pub:7835

Caused by:
    Connection refused (os error 111)
```

_Originally posted by @ekzhang in https://github.com/ekzhang/bore/issues/69#issuecomment-1871686759_

**Comment by ekzhang** [comment]
Can you provide your OS and network details, and IP?

**Comment by ThatOneCalculator** [comment]
I'm fine to provide my OS details here, but is there anywhere where I can privately DM you my IP?

`Arch Linux 6.6.8-native_amd-xanmod1-1 #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 22:25:21 +0000 x86_64 GNU/Linux`

**Comment by ekzhang** [comment]
That's fine! Could you tell me about what kind of network you're on then (home/corporate/public) and what country you're located in? (I assume California)

I think some people had issues connecting from Iran and China, as well as from corporate VPNs in the past

**Comment by ThatOneCalculator** [comment]
Home network in California (Spectrum Internet).

```
❯ ping bore.pub
host bore.pub  # should output 159.223.171.199 or 2604:a880:400:d0::2329:5001
traceroute bore.pub

PING bore.pub (127.0.0.54) 56(84) bytes of data.
64 bytes from 127.0.0.54: icmp_seq=1 ttl=64 time=0.023 ms
64 bytes from 127.0.0.54: icmp_seq=2 ttl=64 time=0.019 ms
64 bytes from 127.0.0.54: icmp_seq=3 ttl=64 time=0.018 ms
^C
--- bore.pub ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2008ms
rtt min/avg/max/mdev = 0.018/0.020/0.023/0.002 ms
bore.pub has address 127.0.0.54
traceroute to bore.pub (127.0.0.54), 30 hops max, 60 byte packets
 1  127.0.0.54 (127.0.0.54)  0.027 ms  0.009 ms  0.007 ms
```

**Comment by ThatOneCalculator** [comment]
> bore.pub has address 127.0.0.54

:thinking:

**Comment by ekzhang** [comment]
That sounds like the problem, haha!

**Comment by ThatOneCalculator** [comment]
Yep, lol... any clue on what to do? Maybe something to add to `/etc/hosts`?

**Comment by ekzhang** [comment]
Quick search suggests that Spectrum's DNS resolvers like arbitrarily blacklist domains for some reason: https://www.reddit.com/r/sysadmin/comments/idiqln/spectrum_dns_servers_resolving_all_records_for_my/?rdt=49955

You could try changing your DNS resolver to 1.1.1.1 (Cloudflare) or 8.8.8.8 (Google) instead?

**Comment by ThatOneCalculator** [comment]
I already use quad9, maybe they're doing some other type of block?

**Comment by ThatOneCalculator** [comment]
Doesn't seem to the be the work of quad9 either

![image](https://github.com/ekzhang/bore/assets/44733677/bb5062d5-cf5f-4341-acff-4b6891726bf5)

**Comment by ekzhang** [comment]
You can confirm with dig:

```
dig @9.9.9.9 bore.pub # works
dig @1.1.1.1 bore.pub # works
```

so just try `dig bore.pub`

**Comment by ThatOneCalculator** [comment]
Turns out systemd thought it would be a fun idea to overwrite my DNS config. All good now, really sorry about the confusion

**Comment by distefam** [comment]
Looks like Quad9 is now blocking bore.pub: https://www.quad9.net/result/?url=bore.pub

**Comment by ThatOneCalculator** [comment]
Requested an unblock
![image](https://github.com/ekzhang/bore/assets/44733677/0d9a61d3-820a-4518-a464-bb8ca256e0cb)

**Comment by ThatOneCalculator** [comment]
This is the reply I got, cc @ekzhang 

```
Hello,
 
Thanks for contacting Quad9 support.
 
The domain is listed on at least 14 threat lists:
https://quad9.net/result?url=bore.pub
https://www.virustotal.com/gui/url/362f9ebe90722c23e3d9a85464857fac8e83c9a666febbf8c7d8b42e57fb08bd?nocache=1
 
The domain administrator will need to contact these threat lists to inquire if there is a false positive, or if there malicious files being served on this domain that need to be removed, which can be done via the following contact points:
 
ThreatSTOP: https://www.threatstop.com/check-ioc
InQuest: https://inquest.net/report-false-positive/?re=bore.pub
CRDF: https://threatcenter.crdf.fr/false_positive.html
FortiGuard: https://www.fortiguard.com/faq/wfratingsubmit?url=DOMAINHERE
CyRadar: https://cyradar.com/contact/
Kaspersky: https://opentip.kaspersky.com/Theunitedwest.org/
Lionic: support@lionic.com
Sophos: https://support.sophos.com/support/s/article/KB-000033422?language=en_US
Webroot/Brightcloud: https://www.brightcloud.com/tools/url-ip-lookup.php
Gridinsoft: https://support-antimalware.com/open.php
 
Once the domain is removed from ThreatSTOP and InQuest, it will be removed from the Quad9 blocklist within a few hours.
 
-Zachary
```

**Comment by ekzhang** [comment]
That's unfortunate. Death to free software projects by overwhelming administrative overhead, I suppose

**Comment by ztheory** [comment]
Zachary from Quad9 here. ThreatSTOP doesn't require you create an account or pay to report an FP. It should prompt you for a 1-time e-mail confirmation to allow you to check the IoC and report FPs; just standard bot prevention.

**Comment by ztheory** [comment]
Glad it worked! We understand this can be a frustrating experience and want to help. Quad9 requires that our threat intelligence partners offer swift response times to FP reports; though, we always recommend filing an FP report with all threat lists on VirusTotal, etc, for the mutual benefit of all parties concerned.

We might recommend hosting a basic webpage on bore.pub with a "Report Abuse" link instead of redirecting to GitHub. This way, netizens will be more inclined to report any links to any malicious files, if that is a use case, to you directly, instead of reporting these files to threat lists.

**Comment by odtmusisi19** [comment]
I am currently developing an Android monitoring application that runs a local Ktor server on port 8080. I am using the bore binary (aarch64-unknown-linux-musl) bundled as a .so file in jniLibs to expose the local port to the internet.

While the local server starts successfully, the bore tunnel fails to establish a connection to the remote server. Here is the relevant log output
```
Server running on port 8080
Error: could not connect to bore.pub:7835
Caused by:
      timed out
```
