### ISSUE TITLE
How hard would it be to support different secrets for each client

### ISSUE THREAD

**Issue by snimavat** [ekzhang/bore#108]
Eg, lets say, I want to add a new client node on demand so it can accept proxied connection. but each client would have different secrets, so that only those users who knows the secret can connect to this client.

**Comment by ekzhang** [comment]
I'm not sure what you mean, bore exposes TCP ports to the public Internet. TCP doesn't have any authentication built into the protocol.

**Comment by snimavat** [comment]
What i meant is `supporting different secret keys for different clients`

Currently bore works like this 

```
# on the server
bore server --secret my_secret_string

# on the client
bore local <LOCAL_PORT> --to <TO> --secret my_secret_string

```


What i am trying to achieve is, `bore server --secret my_secret_string` - but ability to have `multiple` secret things, one for each of my clients accounts, and adding those new secret strings to server on the fly

And for `bore local <LOCAL_PORT> --to <TO> --secret my_secret_string` each client will get own secret key.

**Comment by ekzhang** [comment]
It's not supported
