### ISSUE TITLE
Bad Request  Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

### ISSUE THREAD

**Issue by markmark1** [ekzhang/bore#11]
Bad Request

Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
getting this error for bore local 5000 --to bore.pub
app.py
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.151:5000 (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 130-822-908

**Comment by ekzhang** [comment]
This sounds like an application error on your side. Can you make sure that your request content type is `application/json`? It's a header of the HTTP protocol. `bore` doesn't know anything about HTTP. It'll tunnel raw TCP, and specifying HTTP headers properly is up to you if you use it for that purpose.
