### ISSUE TITLE
Localhost to localhost

### ISSUE THREAD

**Issue by alanmilinovic** [ekzhang/bore#111]
Probably this is not possible but let me ask anyways. :)

Is it possible to forward from localhost to localhost? I have server that is running under VPN and would like to get to the NAT network so that I can normally port forward in ISP Router. Something like this `bore local 8088 --to localhost`. Let's say server and client are on the same machine that is under VPN.

**Comment by ekzhang** [comment]
Hi, I don't quite understand the question! `bore local 8088 --to localhost` does work. But I don't know what you're trying to do specifically?

**Comment by alanmilinovic** [comment]
> Hi, I don't quite understand the question! `bore local 8088 --to localhost` does work. But I don't know what you're trying to do specifically?

Trying to port forward behind VPN.
