### ISSUE TITLE
No, self-hsoting is not as easy as running "bore server"

### ISSUE THREAD

**Issue by Dejagperd** [ekzhang/bore#122]
I have a device in my network, it says it's self hosting bore, but I can't connect to it, the address it gave me does not work for some reason.
I can't find a way to find more debug information other than it's not finding the device.

**Comment by Dejagperd** [comment]
I tried it the other way around and got the error:
failed to lookup address information: No address associated with hostname.
I am looking into that now

**Comment by Dejagperd** [comment]
Android handles hostnames differently, I was trying to get it working using termux on Android and I thought it would be the same.

**Comment by CathyFisher** [comment]
Self-hosting can be complex, requiring more than just running a single command like "bore server"—you need proper networking, security, and infrastructure setup to ensure stability. [Poe the Atlas](https://poehub.org/poe-atlas-map-guide/) presents its own challenges, demanding strategic planning and knowledge to optimize gameplay.
