### ISSUE TITLE
API point to return open connections

### ISSUE THREAD

**Issue by ricardoapaes** [ekzhang/bore#123]
For my use case, I would like to be able to make a request to an api point that responds to a json with the currently active connections.

Is there such a possibility?

**Comment by ekzhang** [comment]
No, feel free to fork for or use case though

**Comment by ricardoapaes** [comment]
@ekzhang I don't know much about programming in Rust, I'm still at the very beginning. Can you give me a tip so I can get started?

**Comment by ekzhang** [comment]
I would recommend checking out the Rust book to get started with learning Rust. This should give you enough background to learn how to modify a small program like bore (400 lines)
