### ISSUE TITLE
Is it possible to close previous connection if a new connection is trying to allocate the same port?

### ISSUE THREAD

**Issue by Lakr233** [ekzhang/bore#125]
The saturation is, i'm using bore as a reverse proxying tool for my server application, behind a complicated firewall and a proxy going through it. Data from local bore will be proxied to bypass the firewall and a server with public IP is then connected to delegate data stream, shown as fig 0.

fig 0: how my bore connect to server
```
                    some | firewall
[bore client]-----[proxy | service]----->[bore server:80]<-----> public access
```

However, upon disconnect, the proxy service may still holds a connection to bore server accepting the heartbeat packet, shown as fig 1. 

fig 1: the proxy service holds the connection and accept the heart beat packet
```
                    some | firewall
[bore client]--x--[proxy | service]----->[bore server:80] <-502-> public access
```

As a result, new connection from bore client is being dropped, shown as fig 2.

fig 2: no more connection possible
```
                    some | firewall
[bore client]--x--[proxy | service]----->[bore server:80] <-502-> public access
[bore client]-----[proxy | service]--x-->[bore server:??] (80 port already used)
```

Sorry for the inconvenience but I failed to learn how to write in Rust, so I'm here to ask for help: Is it possible to close previous connection if a new connection is trying to allocate the same port?

**Comment by ekzhang** [comment]
Not at the moment! bore keeps the existing connections open. You can modify the code if you would like, though I don't think we will merge this into main because `bore` is intended to be read and modified (it's just around 400 lines of code)

**Comment by Lakr233** [comment]
Thanks for your time, while learning to do it myself, I found that rathole fits my needs. Thanks for you reply anyway~

<img width="613" alt="image" src="https://github.com/user-attachments/assets/af808068-855c-4b43-bb11-bda2cf2de574">
