### ISSUE TITLE
Is it possible to serve virtual hosts domains using bore?

### ISSUE THREAD

**Issue by josealgardataborges** [ekzhang/bore#140]
I have several virtual hosts locally hosted with nginx, namelly a.dev, b.dev and c.dev.

Can i use BORE to access them from outside (ie Internet)?

bore local 443 --local-host a.dev --to bore.pub -p 5000
bore local 443 --local-host b.dev --to bore.pub -p 5001
bore local 443 --local-host c.dev --to bore.pub -p 5002

But they don't work, they always show the first VIRTUAL HOST on my nginx configuration file.

PS: i cannot have a.dev run on 8080, then b.dev run on 8081, and c.dev run on 8082.

**Comment by ricardoapaes** [comment]
I had a similar problem and used an nginx container above bore-server.
I'll leave the repository of what I did for you to take a look at: https://github.com/ricardoapaes/bore-server
