### ISSUE TITLE
Forward multiple ports at one bore client command?

### ISSUE THREAD

**Issue by quyvsquy** [ekzhang/bore#142]
Hi,

I've been looking at the code and it seems like running multiple bore commands is necessary to create multiple tunnels (e.g., ports 5001 and 5002) on localhost.

Is there a way to achieve this with a single command? (like `bore local 5001 5002 --to bore.pub`)

Thanks,

**Comment by slendermon** [comment]
Why not just append "&&" after each command? Like e.g. `bore local 5001 5002 --to bore.pub && bore local 5003 5004 --to bore.pub`
