### ISSUE TITLE
stops working after something

### ISSUE THREAD

**Issue by JeromeSchmied** [ekzhang/bore#144]
# bug
## description
After some action (maybe putting my laptop to sleep or simply inactivity) bore stops serving requests
## error
```shell
$ curl bore.pub:$ip
curl: (56) Recv failure: Connection reset by peer
```
## app info
```shell
$ bore --version
bore-cli 0.5.1
```
## system info
```shell
OS: Arch Linux x86_64
Kernel: Linux 6.11.8-arch1-2
Shell: fish 3.7.1
WM: Sway (Wayland)
```

**Comment by ekzhang** [comment]
I think when you put your laptop to sleep, it stops sending Internet traffic to conserve power.
