### ISSUE TITLE
stops serving requests

### ISSUE THREAD

**Issue by JeromeSchmied** [ekzhang/bore#145]
# bug

Sorry, had to open a new one because #144 has been closed, but not resolved.
This problem also happens if the machine doesn't go to sleep.

## description

After something `bore` stops serving requests

## error
> [!note]
> the server and the request are on the same machine
```sh
$ curl bore.pub:$ip
curl: (56) Recv failure: Connection reset by peer
```
## app info
```sh
$ bore --version
bore-cli 0.5.1
```
## system info
```sh
OS: Arch Linux x86_64
Kernel: Linux 6.11.8-arch1-2
Shell: fish 3.7.1
WM: Sway (Wayland)
```

**Comment by ekzhang** [comment]
> After something `bore` stops serving requests

There are not enough details in this bug report to resolve.

**Comment by ekzhang** [comment]
Bore is over 2.5 years old and we haven't seen any issues of transient disconnects. I think it might be a problem with your network. If you have a reproduction script on cloud hardware perhaps, we can reopen the issue.

**Comment by JeromeSchmied** [comment]
> > After something `bore` stops serving requests
> 
> There are not enough details in this bug report to resolve.

I completely agree.
How may I provide some?

**Comment by ekzhang** [comment]
> Bore is over 2.5 years old and we haven't seen any issues of transient disconnects. I think it might be a problem with your network. If you have a reproduction script on cloud hardware perhaps, we can reopen the issue.

**Comment by JeromeSchmied** [comment]
I've been actually looking for an answer like: `RUST_LOG=trace bore <cmd>` but no worries, I've figured it myself. 

And so kinda found the source of the issue as well.

Indeed **it is the network's problem**, as if for just a moment the wifi is glitching (not turned off and then back on, from that `bore` recovers succesfully) `bore` stops polling or how to say it.

*I'm currently looking for a way in which this could be reproducted.*
*I'll soon provide some logs as well.*

**Comment by chmac** [comment]
We're running our own bore server and two bore clients. We notice that at least one of those always seems to fail over. We rarely use it, but after some weeks, the tunnel seems to have failed. Restarting bore on the client machine brings the connection back up right away.

Both of these are servers, although one is on a DSL line and one on a DSL line and then over a VPN. Is there anything we can do to figure out what might cause the issue? Or can we set something up to keep the connection alive?

**Comment by ekzhang** [comment]
https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9
