### ISSUE TITLE
Feature: Support of additional hosts

### ISSUE THREAD

**Issue by rajeshisnepali** [ekzhang/bore#21]
It would be nice if it support others hosts apart from localhost.

![image](https://user-images.githubusercontent.com/23610013/163128553-3aa68755-5900-4910-8058-1bce4bdec2df.png)

In [readme](https://github.com/ekzhang/bore#local-forwarding) it says it support hosts, but it doesn't work

**Comment by bolshoytoster** [comment]
@rajeshisnepali from the `-h` output it doesn't look like you're using a supported version.

Currently there aren't any releases that have this feature, as it was added [yesterday](https://github.com/ekzhang/bore/pull/15) so you'll have to `git clone`/[download the zip](https://github.com/ekzhang/bore/archive/refs/heads/main.zip) to get the latest code.

**Comment by rajeshisnepali** [comment]
Package can be found in `bore-main/target/debug/bore`

**Comment by ekzhang** [comment]
You can run `cargo install --git https://github.com/ekzhang/bore` to install from the latest source code as well :)
