### ISSUE TITLE
Feature request: support custom control port

### ISSUE THREAD

**Issue by mantou132** [ekzhang/bore#22]
e.g: 443

**Comment by bolshoytoster** [comment]
@mantou132 you can change the constant in `src/shared.rs`:
https://github.com/ekzhang/bore/blob/2d0dcf9889dcdb3b202d69163f7f071d09facb83/src/shared.rs#L13-L15

I could make it variable, probably through a command line option if there's no reason it can't be changed @ekzhang.

**Comment by hkcomori** [comment]
I want this feature too.
Currently, bore cannot be used in a network where the control port is blocked.
I want to avoid this by choosing a port that is less restrictive (eg 443).

**Comment by bolshoytoster** [comment]
@hkcomori as I suggested, if you don't mind compiling it yourself, you can change the `CONTROL_PORT` constant.
https://github.com/ekzhang/bore/blob/9cd43f458a7f15142ab9e9c03f58a35c94ffbe4a/src/shared.rs#L16-L18
