### ISSUE TITLE
mention HTTP support

### ISSUE THREAD

**Issue by Hunam6** [ekzhang/bore#29]
What about builtin http support? This would make this tool useful for web devs as well.

**Comment by Hunam6** [comment]
BTW this is a wonderful tool congrats 👏

**Comment by BxOxSxS** [comment]
You can route port with http server using bore

**Comment by Hunam6** [comment]
Oh my bad you're right, what do you think about mentioning it in the docs?

**Comment by BxOxSxS** [comment]
TCP tunnel that expose local ports is Imo enough description

**Comment by Hunam6** [comment]
I personally don't find it so intuitive, I've submitted a PR, @ekzhang will decide.
