### ISSUE TITLE
Unbounded byte buffer in read_until

### ISSUE THREAD

**Issue by cedric05** [ekzhang/bore#32]
calling read_until reads all until it reaches null byte. it will cause memory leaks. 
Use [AnyDelimiterCodec](https://docs.rs/tokio-util/0.7.1/tokio_util/codec/struct.AnyDelimiterCodec.html)
```rust
let mut framed_stream = Framed::new(connect_with_timeout(to, CONTROL_PORT).await?, AnyDelimiterCodec::new_with_max_length(vec![0], vec![0], 200));
```

ref: https://github.com/ekzhang/bore/blob/e25f021505fdc3f4e7f5f32c1a4d4b865bd84357/src/shared.rs#L73

**Comment by ekzhang** [comment]
Can you give an example of a memory leak? I don't believe the line you linked leaks memory, since `buf` is dropped properly regardless of what happens in `read_util`.

**Comment by cedric05** [comment]
Framed manages read_until via `.next` call.  
it also can set limit to all upcoming frames and fails with `AnyDelimiterCodecError` if length is overflowed.

Here is my approach https://github.com/ekzhang/bore/pull/33.

**Comment by ahmed1107** [comment]
> Framed manages read_until via `.next` call. it also can set limit to all upcoming frames and fails with `AnyDelimiterCodecError` if length is overflowed.
> 
> Here is my approach #33.

nice, looks clean
