### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by austinyan** [ekzhang/bore#34]
OS: uname -a 
Linux instance-20210901-1753 5.8.0-1037-oracle #38~20.04.1-Ubuntu SMP Fri Jul 16 01:02:14 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
cargo 1.57.0

$ cargo install bore-cli
    Updating crates.io index
  Installing bore-cli v0.3.0
   Compiling version_check v0.9.4
   Compiling proc-macro2 v1.0.37
   Compiling unicode-xid v0.2.2
   Compiling libc v0.2.123
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.91
   Compiling typenum v1.15.0
   Compiling lazy_static v1.4.0
   Compiling log v0.4.16
   Compiling memchr v2.4.1
   Compiling serde_derive v1.0.136
   Compiling smallvec v1.8.0
   Compiling parking_lot_core v0.9.2
   Compiling cc v1.0.73
   Compiling serde v1.0.136
   Compiling subtle v2.4.1
   Compiling scopeguard v1.1.0
   Compiling adler v1.0.2
   Compiling gimli v0.26.1
   Compiling heck v0.4.0
   Compiling hashbrown v0.11.2
   Compiling serde_json v1.0.79
   Compiling once_cell v1.10.0
   Compiling pin-project-lite v0.2.8
   Compiling rustc-demangle v0.1.21
   Compiling anyhow v1.0.56
   Compiling os_str_bytes v6.0.0
   Compiling ansi_term v0.12.1
   Compiling termcolor v1.1.3
   Compiling bitflags v1.3.2
   Compiling cpufeatures v0.2.2
   Compiling ryu v1.0.9
   Compiling bytes v1.1.0
   Compiling itoa v1.0.1
   Compiling textwrap v0.15.0
   Compiling strsim v0.10.0
   Compiling hex v0.4.3
   Compiling generic-array v0.14.5
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling lock_api v0.4.7
   Compiling miniz_oxide v0.4.4
   Compiling indexmap v1.8.1
   Compiling tracing-core v0.1.26
   Compiling sharded-slab v0.1.4
   Compiling backtrace v0.3.64
   Compiling thread_local v1.1.4
   Compiling addr2line v0.17.0
   Compiling clap_lex v0.1.1
   Compiling quote v1.0.18
   Compiling tracing-log v0.1.2
   Compiling num_cpus v1.13.1
   Compiling getrandom v0.2.6
   Compiling mio v0.8.2
   Compiling atty v0.2.14
   Compiling socket2 v0.4.4
   Compiling object v0.27.1
   Compiling tracing-subscriber v0.3.11
   Compiling parking_lot v0.12.0
   Compiling crypto-common v0.1.3
   Compiling block-buffer v0.10.2
   Compiling tokio-macros v1.7.0
   Compiling tracing-attributes v0.1.20
   Compiling dashmap v5.2.0
   Compiling digest v0.10.3
   Compiling clap_derive v3.1.7
   Compiling tokio v1.17.0
   Compiling sha2 v0.10.2
   Compiling hmac v0.12.1
   Compiling tracing v0.1.34
   Compiling clap v3.1.9
   Compiling uuid v0.8.2
   Compiling bore-cli v0.3.0
error: there is no argument named `message`
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bore-cli-0.3.0/src/client.rs:56:73
   |
56 |             Some(ServerMessage::Error(message)) => bail!("server error: {message}"),
   |                                                                         ^^^^^^^^^

error: there is no argument named `to`
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bore-cli-0.3.0/src/client.rs:64:29
   |
64 |         info!("listening at {to}:{remote_port}");
   |                             ^^^^

error: there is no argument named `remote_port`
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bore-cli-0.3.0/src/client.rs:64:34
   |
64 |         info!("listening at {to}:{remote_port}");
   |                                  ^^^^^^^^^^^^^

error: there is no argument named `to`
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bore-cli-0.3.0/src/client.rs:130:52
    |
130 |     .with_context(|| format!("could not connect to {to}:{port}"))
    |                                                    ^^^^

error: there is no argument named `port`
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bore-cli-0.3.0/src/client.rs:130:57
    |
130 |     .with_context(|| format!("could not connect to {to}:{port}"))
    |                                                         ^^^^^^

error: could not compile `bore-cli` due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bore-cli v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-installaFExns`

Caused by:
  build failed

**Comment by praveenperera** [comment]
Upgrade to at least Rust 1.58

ttps://github.com/ekzhang/bore/issues/7
https://github.com/ekzhang/bore/issues/24

**Comment by austinyan** [comment]
> Upgrade to at least Rust 1.58
> 
> #7 #24

Thanks @praveenperera
