### ISSUE TITLE
Feature request: Add systemd service unit

### ISSUE THREAD

**Issue by jie65535** [ekzhang/bore#36]

**Comment by jie65535** [comment]
Thank you very much.

 I'm not familiar with Linux so I raised this issue, thanks for the tip.

**Comment by avidseeker** [comment]
> I personally wrote a systemd service unit that I use to deploy the "bore.pub" server

You can also include an environment file `/etc/default/bore` that contains the secret.
```
[Unit]
Description=bore service
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=bore server
EnvironmentFile=/etc/default/bore
Restart=always
User=root

[Install]
WantedBy=default.target
```
