### ISSUE TITLE
local to reconnect to server

### ISSUE THREAD

**Issue by kalmarz** [ekzhang/bore#37]
Hey, I'm wondering if there's a way (at least on the roadmap) for `local` to reconnect to the `server` if something comes into the way? My local stuff is inside the home network and the `server` runs on a VPS out in the wild. When I'm not home while the `server` restarts, I loose connection until I get back and also restart the `local`.

**Comment by jie65535** [comment]
Maybe you can use `systemd` to daemonize the client

**Comment by kalmarz** [comment]
that's nice, thank you. however I run `local` on a Kubernetes cluster.

**Comment by kalmarz** [comment]
Anyways, the latest build seemingly doesn't have reconnection issues. I works perfectly on the cluster, picks up the connection when the `server` comes back alive.
