### ISSUE TITLE
bore on Kubernetes

### ISSUE THREAD

**Issue by kalmarz** [ekzhang/bore#41]
I'm wondering if creating a PR about how to run bore on a Kubernetes cluster would be interesting for the project?

I run all my stuff on k8s in my home network so I had to figure out the way of running bore too. I can create a README with the deployment instructions, including the Kubernetes manifest files.

**Comment by praveenperera** [comment]
I'd personally be interested in that @kalmarz

**Comment by ekzhang** [comment]
That sounds useful, especially since it involves some nontrivial network setup. It also aligns with the goal of `bore` to be understandable to as many people as possible. If you write a clear, focused, and well-typed Markdown doc then I'm happy to merge it in.
