### ISSUE TITLE
powerpc support?

### ISSUE THREAD

**Issue by shyn** [ekzhang/bore#47]
bore is awesome!

My router and NAS chips are powerpc32 chips. So it will be great to be supported. 

I am a noob to rust.  Don't know if it's easy to port to powerpc. Thanks in advance if you guys make it!

**Comment by orhun** [comment]
There are a couple of targets listed for `powerpc` on [Platform Support](https://doc.rust-lang.org/nightly/rustc/platform-support.html) page. You can either pick one of them and try to build (with e.g. `--target powerpc-unknown-linux-gnu`) or the build matrix in the [continuous deployment workflow](https://github.com/ekzhang/bore/blob/main/.github/workflows/mean_bean_deploy.yml) can be changed for distributing binary releases for `powerpc`.  Of course it is up to @ekzhang to whether specifically support `powerpc` or not. I didn't try compiling `bore` for `powerpc` but just wanted to point out the possible ways :)

**Comment by shyn** [comment]
@orhun thx for your information! Looks like `powerpc-unknown-linux-gnu` is supported as Tier2! Will try it soon myself.
