### ISSUE TITLE
I could not figure out how to start a boron server on the local network with the selected address and port

### ISSUE THREAD

**Issue by DmitrySorda** [ekzhang/bore#54]
`~ % bore server                            
2022-09-16T17:46:16.464695Z  INFO bore_cli::server: server listening addr=0.0.0.0:7835`

`~ % bore local 1234 --to 0.0.0.0:7835
Error: could not connect to 0.0.0.0:7835:7835

Caused by:
    failed to lookup address information: nodename nor servname provided, or not known
`

**Comment by ekzhang** [comment]
Could you try connecting to 127.0.0.1:7835 instead of 0.0.0.0?

**Comment by DmitrySorda** [comment]
```
~ % bore server                                   
2022-09-17T10:20:36.858783Z  INFO bore_cli::server: server listening addr=0.0.0.0:7835
```
```
~ % bore local 1234 --to 127.0.0.1:7835
Error: could not connect to 127.0.0.1:7835:7835

Caused by:
    failed to lookup address information: nodename nor servname provided, or not known
```
Could there be a problem with the macos I'm using?

If I run it like below, without specifying a port, it works, but I still can't figure out how to choose a port for the server
```
~ % bore local 1234 --to 127.0.0.1     
2022-09-17T10:25:24.894038Z  INFO bore_cli::client: connected to server remote_port=52569
2022-09-17T10:25:24.906120Z  INFO bore_cli::client: listening at 127.0.0.1:52569
```

**Comment by ekzhang** [comment]
Ah, I see the problem. You're getting the port there twice. It should just be "bore local 1234 --to 127.0.0.1" or "--to localhost"

**Comment by DmitrySorda** [comment]
Do I understand correctly that the Bore Local 1234 is an indication to the client to open 1234 locally, and --to 127.0.0.1 is this address of a remote server? I am trying to create a port of me on a remote server, but I only manage to create default: 7835.
Team
```
~ % bore server —min-port 1234
2022-09-18T12:14:23.044547Z  INFO bore_cli::server: server listening addr=0.0.0.0:7835
```
He creates the server and launches it on the default port 7835 and I thought that it was possible, as it should work, and the client already indicates the desired port and if he is free, the system provides it.
In the end, I cannot figure out how to launch a server with the desired port either on the server side or from the client

**Comment by ekzhang** [comment]
Hi Dmitry, you're correct. The remote server creates a control port at 7835. Then you need to pass in an IP or DNS for the machine running `bore server`. In your case you are running `bore server` on your local machine, so you can pass in `localhost` or `127.0.0.1`, which is the loopback address.

For example, assume you had two machines A and B, with mutually accessible IP addresses `10.0.0.61` and `10.0.0.62`. Then you could run:

```
# on machine A, concurrently
$ bore server
$ bore local 1234 --to 127.0.0.1
```

This would forward machine A's port 1234 to a free port on machine A. Or you could run:


```
# on machine A
$ bore server

# on machine B
$ bore local 1234 --to 10.0.0.61
```

This would forward machine B's port 1234 to a free port on machine A.

**Comment by DmitrySorda** [comment]
Thank you very much for your attention and patient answers to my questions. My English is bad (sorry) and I can't make my question clear, but if I take this example
```
# on machine A
$ bore server

```
```
# on machine B
$ bore local 1234 --to 10.0.0.61
```
then my question boils down to how to set your port number to 10.0.0.61 on machine A?

**Comment by ekzhang** [comment]
> my question boils down to how do I point my port number to 10.0.0.61 on machine A?

I think there is a misunderstanding. The number 10.0.0.61 is an _IP address_, rather than a port number. An IP address is a way of locating a computer on the Internet.

If you are running `bore server` on machine A, then to make a port `1234` on machine B available on machine A, you need to pass in machine A's IP address to the `bore local` command. Your IP address is something that is administered by your Internet service provider or cloud provider.

Note that machine A needs to be accessible from the public Internet.

**Comment by DmitrySorda** [comment]
I understand, but can I specify the port number on the remote ip address?

**Comment by ekzhang** [comment]
There are two ports, one control port `7835` used internally by bore and one remote port where your application is forwarded. You cannot set the former, but you can set the latter with the `--port` argument.

```
➜  ~ bore local 3000 --to bore.pub --port 19473
2022-09-18T14:22:04.737628Z  INFO bore_cli::client: connected to server remote_port=19473
2022-09-18T14:22:04.737677Z  INFO bore_cli::client: listening at bore.pub:19473
```

**Comment by DmitrySorda** [comment]
Thank you very much! This is what I wanted
