### ISSUE TITLE
feature. support encrypt of messages

### ISSUE THREAD

**Issue by cutepig123** [ekzhang/bore#55]
as title. is it possible to encrypt the messages between tunnel client and server?

**Comment by ekzhang** [comment]
No, `bore` deals with raw TCP streams and is therefore unencrypted. See the README section below.

> On a custom deployment of bore server, you can optionally require a secret to prevent the server from being used by others. The protocol requires clients to verify possession of the secret on each TCP connection by answering random challenges in the form of HMAC codes. (This secret is only used for the initial handshake, and no further traffic is encrypted by default.)

This is therefore out of scope. TCP provides reliable, unencrypted byte streams. If you would like encryption, you can use any encryption mechanism on the application layer that runs on top of TCP. For example, TLS.
