### ISSUE TITLE
bore and bore-cli

### ISSUE THREAD

**Issue by delan** [ekzhang/bore#57]
Hi, I’m the author of [bore](https://crates.io/crates/bore), another Rust CLI in the networking space. I’ve been working on my next release for the last couple months, but I’m worried our projects having the same name might lead to some confusion.

Do you have any thoughts around how we can work together? Thanks!

**Comment by ekzhang** [comment]
Hi Delan, thanks for reaching out. I wasn't aware of [bore](https://crates.io/crates/bore) the networking CLI tool. Unfortunately it might be too late for me to change the name of this repository since I already have the domain `bore.pub` and everything else.
