### ISSUE TITLE
Ceveats/pricing?

### ISSUE THREAD

**Issue by julianfairfax** [ekzhang/bore#62]
Hi,

It appears you have created a free, open source, tunnelling service, with no bandwidth limits. Is this the case? Or are there caveats to this service (I wouldn't blame you for putting a bandwidth limit)? What about the privacy aspects? Is everything end-to-end encrypted?

If there are caveats, is there a form of paid plan to remove those? I would self-host, but I'm looking into this tool specifically because my ISP wants to make me pay for port forwarding, something I find a bit ridiculous.

I don't want to use your tool and pass a lot of bandwidth through if that's not what it's for, or not what it can support, but if that is possible, I will probably look into it. I want my file server to be accessible from the outside, and I don't think what my ISP is doing is right.

In any case, thank you for developing this tool!

**Comment by ekzhang** [comment]
> Hi,
> 
> It appears you have created a free, open source, tunnelling service, with no bandwidth limits. Is this the case? Or are there caveats to this service (I wouldn't blame you for putting a bandwidth limit)? What about the privacy aspects? Is everything end-to-end encrypted?

Be reasonable with usage. Obviously there are limits to anything, it cannot be used for 100 GB/second of data for example, the public instance will be throttled. But if you're running into problems with it you are probably creating problems for other people as well.

Bore is intentionally extremely minimal and unopinionated. It only proxies TCP. If you want end-to-end encryption (e.g., through TLS), you can do that with bore but you need to implement TLS yourself. TLS runs on top of TCP.

> If there are caveats, is there a form of paid plan to remove those? I would self-host, but I'm looking into this tool specifically because my ISP wants to make me pay for port forwarding, something I find a bit ridiculous.

We don't offer a paid plan, there are several startup companies that offer tunneling and private networking services to business users though.

> I don't want to use your tool and pass a lot of bandwidth through if that's not what it's for, or not what it can support, but if that is possible, I will probably look into it. I want my file server to be accessible from the outside, and I don't think what my ISP is doing is right.

You can try using it but it's mostly for one-off transient usage; for example, `bore` doesn't allow you to reserve a specific port permanently, so if someone else takes the port you won't be able to use it.

> In any case, thank you for developing this tool!

💚
