### ISSUE TITLE
Add `scoop` under Installation instructions

### ISSUE THREAD

**Issue by Animesh-Ghosh** [ekzhang/bore#63]
Hi, 

Thank you for making `bore` and also hosting the http://bore.pub service.

I have packaged `bore` to be installable on Windows using the [Scoop](https://github.com/ScoopInstaller/Scoop) CLI installer and added it to my [kulfi-scoop](https://github.com/Animesh-Ghosh/kulfi-scoop) bucket.

I was wondering if we could add that as one of the sources for installing `bore` on Windows?

Thanks again!

**Comment by ekzhang** [comment]
Sure, that would be great! Do you have a link to your installation instructions that I can include in the README?

**Comment by Animesh-Ghosh** [comment]
Yeah, the installation instructions are there on my repository's [README](https://github.com/Animesh-Ghosh/kulfi-scoop#readme).

Just replacing the example app's name to `bore` should be enough:
```pwsh
scoop bucket add kulfi-scoop https://github.com/Animesh-Ghosh/kulfi-scoop

scoop install bore
```

We'd have to let the users know though that they need to install [scoop](https://scoop.sh) too

**Comment by ekzhang** [comment]
> ```powershell
> scoop bucket add kulfi-scoop https://github.com/Animesh-Ghosh/kulfi-scoop
> 
> scoop install bore
> ```
> 
> We'd have to let the users know though that they need to install [scoop](https://scoop.sh) too

Could you put these instructions in your README so that I can link to them directly, under a heading?

**Comment by Animesh-Ghosh** [comment]
So, that bucket has other apps too. Not sure if adding instructions only for `bore` would make sense. Would it be better to add the instructions on `bore`'s README instead?

Something like:
```markdown
# Installation
.
.
.
If you're on Windows, you can install `bore` via [Scoop][https://github.com/ScoopInstaller/Scoop]:
`scoop install bore`
```

**Comment by ekzhang** [comment]
You can add instructions for each of the apps in the bucket then? Otherwise I don't think it would be suitable to add

```
scoop bucket add kulfi-scoop https://github.com/Animesh-Ghosh/kulfi-scoop
```

to bore's README since that doesn't really have anything to do with `bore` and you'd need to update it manually on bore's side whenever you made a change to your repository.

**Comment by Animesh-Ghosh** [comment]
I think an example would make much clearer about what I had in mind.
Something like [this](https://github.com/nektos/act#scoop-windows) was what I wanted to get added to `bore`'s README, not the instructions to add the bucket 😅 .

**Comment by ekzhang** [comment]
I would be happy to do that if `scoop install bore` worked right now! But it doesn't seem like that bore was added to the main repository.

**Comment by Animesh-Ghosh** [comment]
Would linking to my bucket do? So instead of pointing to [ScoopInstaller/Main](https://github.com/ScoopInstaller/Main), the installation link would point to [Animesh-Ghosh/kulfi-scoop](https://github.com/Animesh-Ghosh/kulfi-scoop)?

**Comment by Animesh-Ghosh** [comment]
Ah, NVM. Seems like people had already packaged `bore` according to the app search result [here](https://scoop.sh/#/apps?q=bore&s=0&d=1&o=false).

**Comment by ekzhang** [comment]
> Would linking to my bucket do? So instead of pointing to [ScoopInstaller/Main](https://github.com/ScoopInstaller/Main), the installation link would point to [Animesh-Ghosh/kulfi-scoop](https://github.com/Animesh-Ghosh/kulfi-scoop)?

Just to be clear I'd be happy to do this if you wanted, I would just want more clear instructions in the README of that repository.
