### ISSUE TITLE
tracing colors cannot be suppressed

### ISSUE THREAD

**Issue by ciis0** [ekzhang/bore#65]
I am running bore to expose local ports to a remote Windows server and it works quite well, thank you!

The only annoyance I have noticed that log/tracing colors do not seem to be able to be turned off, which make the log files look funny when for example wrapping bore in WinSW (for running as a Windows service).

![image](https://user-images.githubusercontent.com/16290850/204883684-348ab258-8b54-49d7-858b-ffc6500c9ed7.png)

I tried `NO_COLOR`, that only affects the help colors; but that does not affect tracing: https://github.com/tokio-rs/tracing/issues/2388.

Opening this issue to make you aware of that so it could be fixed when there is a fix in tokio tracing. :)

**Comment by ekzhang** [comment]
I'm glad it's working well for you! That's awesome :)

I didn't realize that tracing-subscriber had no way to turn off colors via environment variable. Sounds like the upstream issue has some activity so I think we could wait and see, and I'm happy to publish a release of bore when tracing is updated.

**Comment by silasalberti** [comment]
I had Devin investigate this and seems like it's now fixed upstream. It tested the version upgrade locally and I created a PR (#146): https://preview.devin.ai/sessions/2b78db994f0848bfbd2b181fc33dc044
