### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by bropines** [ekzhang/bore#66]
I probably have a stupid question again. Is it possible to add support for ssl certificates as in localtunnel? Or is it already there and I'm really stupid that I didn't find it?

**Comment by ekzhang** [comment]
(Assuming you mean TLS, not SSL, which is insecure and was deprecated in 2015.) There's no built-in support for TLS certificates in `bore`. You would need to either handle them yourself, or use `bore` as a starting point for a more fully-featured software tailored to your needs.

**Comment by xamgore** [comment]
I would like to show a website I'm working on for a friend of mine. Due to some technical limitations it needs HTTP/2 thus TLS. What's the best way to handle it with bore?
