### ISSUE TITLE
Public instance is being used for lots of traffic

### ISSUE THREAD

**Issue by ekzhang** [ekzhang/bore#68]
Recently (in the past month) I've gotten bills for **1.5 TB of data transfer** from the public instance of bore, at `bore.pub`.

If I had deployed this on AWS, there would be problems because it would be costing me between $100-$200. However I anticipated that there would be some traffic, so I deployed it on DigitalOcean specifically to take advantage of their low pricing on network egress at $0.01/GB, which is 10x cheaper than other cloud offerings.

However, 1.5 TB is way more than I was expecting for usage of this service. So this is a gentle reminder that if you're using the public instance of bore, try to use it for its intended purpose, which is as a short-lived way to expose ports to the Internet. Please respect other users and be reasonable with how much data you transfer.

_By the way, if you'd like to help me keep bore running, any amount of contribution through [GitHub Sponsors](https://github.com/sponsors/ekzhang) would be very much appreciated. Even $1/month lets me support 100 GB of network transfer through the public instance._ :)

I really don't want to shut the public service down, and I won't unless the costs are significantly higher than they are now, but here's a warning regardless before we get too close the point of what I'm willing to spend on a free, hobby service.

**Comment by MarcusCemes** [comment]
Thanks for making `bore.pub` public.

Have you considered hosting the VPS on [Hetzner](https://www.hetzner.com/cloud)? I did an analysis a while back, they have some of the lowest bandwidth costs that I could find. I've been hosting my website with them for years and have no complaints.

**Comment by SeriousBug** [comment]
I'd also suggest OVH Cloud, which has no bandwidth costs.

**Comment by ekzhang** [comment]
Another bump, last month we suddenly saw a usage of **2.8 TB per month**. If you're seeing this and sending a lot of traffic over bore, please reduce your usage! :)
