### ISSUE TITLE
Is there a problem with the server? It stopped working.

### ISSUE THREAD

**Issue by ShriramKhandbahale** [ekzhang/bore#69]
$ bore local 8080 --to bore.pub

Error: could not connect to bore.pub:7835

Caused by:
    timed out

**Comment by ekzhang** [comment]
I'm not able to reproduce, it's still working for me.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/7550632/216059515-1d2b9f15-2757-40f1-9386-09d11febeabd.png">

**Comment by ekzhang** [comment]
I think it's more likely that your Internet connection was out.

**Comment by ThatOneCalculator** [comment]
Is it down now?

```
❯ bore local --to bore.pub 3001
Error: could not connect to bore.pub:7835

Caused by:
    Connection refused (os error 111)
```

**Comment by ekzhang** [comment]
Nope!

```
$ bore local --to bore.pub 3001
2023-12-29T02:40:19.923253Z  INFO bore_cli::client: connected to server remote_port=47882
2023-12-29T02:40:19.923295Z  INFO bore_cli::client: listening at bore.pub:47882
```
