### ISSUE TITLE
More info please

### ISSUE THREAD

**Issue by skironDotNet** [ekzhang/bore#71]
I like the project, but I'm trying to understand life use case scenario. Despite all the description is not clear to me. Does it support SSL, can you provide real use case scenario?
Can I tunnel specific port?
For example I have employer machine with zscaler proxy (like VPN) that puts me in the company network so I can access let say SQL database. Can I tunnel the specific port from employer machine to my personal machine so I could make a SQL connection from my personal?

**Comment by ekzhang** [comment]
> I like the project, but I'm trying to understand life use case scenario. Despite all the description is not clear to me. Does it support SSL, can you provide real use case scenario?

The tool tunnels TCP to the public Internet past a NAT firewall. That is all it does. TLS is a protocol on top of TCP. You can serve TLS yourself on bore, but bore is unaware of these certificates and won't do the TLS termination itself.

> Can I tunnel specific port? For example I have employer machine with zscaler proxy (like VPN) that puts me in the company network so I can access let say SQL database. Can I tunnel the specific port from employer machine to my personal machine so I could make a SQL connection from my personal?

No, you can use `ssh` for that
