### ISSUE TITLE
Reverse Proxy Support

### ISSUE THREAD

**Issue by DesignsWithDavid** [ekzhang/bore#72]
I would like to see the ability to forward local ports to a custom random path instead of a random port to allow support of domains that run other services behind a reverse proxy.   

For example, when forwarding a local port (say `5000`) to `bore.pub`, instead of the resulting URL being `bore.pub:12345`, it could be `proxy.bore.pub/12345/`.  This could be a challenge given that applications at the local port would likely request content at a different path, but reverse proxies, like Traefik, already support path modifications.  Alternatively, subdomains could be generated(i.e. `abc.proxy.bore.pub`), but that requires a more complicated SSL configuration.

**Comment by DesignsWithDavid** [comment]
I would be willing to contribute to this feature, but I want to be sure it is something others are interested in, and that the maintainers would actually entertain such a pull request.

**Comment by MrZeusTheCoder** [comment]
+1

**Comment by ekzhang** [comment]
> I would like to see the ability to forward local ports to a custom random path instead of a random port to allow support of domains that run other services behind a reverse proxy.
> 
> For example, when forwarding a local port (say `5000`) to `bore.pub`, instead of the resulting URL being `bore.pub:12345`, it could be `proxy.bore.pub/12345/`.

Hi, thanks for the idea. Bore does not speak HTTP, it only operates at the TCP level. This is an explicit design choice and is intended this way because the software is to be as minimal and general as possible. So it's not actually possible to support this, since "paths" are not a concept in TCP.
