### ISSUE TITLE
[Idea] Show url with "http://"

### ISSUE THREAD

**Issue by AirOne01** [ekzhang/bore#74]
Idea:

When bore starts listening, (say, at `bore.pub:9999`), show the url with `http://` before (i.e `http://bore.pub:9999`).
This allows for terminals with clickable link support to allow users to click on the link, instead of having to copy it.

I know that this will not work for every case, as the port bore is talking to does not necessarily use HTTP, and that bore needs a way to recognize a port as using HTTP, without compromising traffic or sending too many requests, which might invalidate or falsify any analytics data or logs.

Note that this concept could be applied to multiple protocols, even though it might be overkill.

**Comment by ekzhang** [comment]
Thanks for the feature suggestion! It's a really creative suggestion that I haven't thought of before.

Unfortunately because bore is intended to be minimal, I don't think it makes sense to include features like auto-detecting HTTP protocol.
