### ISSUE TITLE
Custom self hosted server port.

### ISSUE THREAD

**Issue by bropines** [ekzhang/bore#82]
What is the problem, when using the self-hosted version the client always goes to port `7835`, but I configured nginx to send me to port 7835 on the server bore.domain.com and I connect to `80`. But the client defaults to `7835` and tells me to fuck off
![image](https://user-images.githubusercontent.com/57861007/236678685-f349ac2e-c6eb-4ec6-8773-f3e6decd2976.png)

**Comment by ekzhang** [comment]
Hi, happy to talk to you about this, but please do not use language like "fuck off" — if you could make a new issue without those words I would be happy to help.
