### ISSUE TITLE
Custom self hosted server port(cultural)

### ISSUE THREAD

**Issue by bropines** [ekzhang/bore#83]
What is the problem, when using the self-hosted version the client always goes to port 7835, but I configured nginx to send me to port 7835 on the server bore.domain.com and I connect to 80. But the client defaults to 7835. 

PS. Yandex translator is extremely cultural, sorry.
![image](https://user-images.githubusercontent.com/57861007/236691085-75d08182-2b78-4ace-9f88-f7ef3e72b6fa.png)

**Comment by bropines** [comment]
The documentation says that it works on port 7835, but what if I want to close the tunnel under cloudflare for example and it by default allows only ports 443 and 80 (or more if you buy a subscription).

**Comment by ekzhang** [comment]
Hi, thanks for asking again with more details. Yes, `bore` only works with control port `7835`, and this is not configurable. The `--to` option only takes a hostname or IP address and not a port as argument.
