### ISSUE TITLE
How we get list and delete route?

### ISSUE THREAD

**Issue by tecnicosya** [ekzhang/bore#84]
Please add an option to list the routes we serving and possibility to ban or delete a rule.

**Comment by ys928** [comment]
Maybe you could try [stab](https://github.com/ys928/stab)

**Comment by ekzhang** [comment]
re: deleted comment — Making forks is fine but please do not use bore's code without following the terms of the license

**Comment by ys928** [comment]
Sorry, I did learn part of bore's implementation logic, but the code was still ultimately implemented by me and did not copy bore's code, so I don't think it violates bore's protocol.Is the power to learn code not even allowed?
















At 2024-04-06 00:31:25, "Eric Zhang" ***@***.***> wrote:

re: deleted comment — Making forks is fine but please do not use bore's code without following the terms of the license
