### ISSUE TITLE
Error: frame error, invalid byte length

### ISSUE THREAD

**Issue by JArmandoCl** [ekzhang/bore#85]
At first thanks for this awesome tool, actually i´m getting disconnected after some time working in local pc, error in CMD shows Error: frame error, invalid byte length

![Imagen de WhatsApp 2023-05-31 a las 18 15 07](https://github.com/ekzhang/bore/assets/58884118/35003c93-bfe7-4f36-bf4e-f6c32ef09c85)

**Comment by ekzhang** [comment]
Ah, so the problem is caused by the next message (os error 10054). When trying to read the next byte of data from the server (length of a frame), there was an error:

```
se ha forzado la interrupción de una conexión existente por el host remoto
```

Likely there was a brief disconnection between your machine and `bore.pub`.
