### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by AmirRezaM75** [ekzhang/bore#87]
when running ``./bore local 5173 --to bore.pub`` command I get following error after 2 seconds

Error: timed out waiting for initial message
Caused by:
    deadline has elapsed

**Comment by ekzhang** [comment]
Hm, it looks like you're having issues making a connection to the public bore server. Perhaps check network connection and firewall?

**Comment by kvn1351** [comment]
Same issue. All other tunneling services work.

**Comment by ekzhang** [comment]
Unhelpful comments are not welcomed, please make a new issue with proper details that can be actually debugged.
