### ISSUE TITLE
Suggestion: add "auto retry when disconnected" function

### ISSUE THREAD

**Issue by qwinwin** [ekzhang/bore#90]
Sometimes there is a problem with the device network and the network will be disconnected. And bore will disconnected in this situation even the network recover in minites.

**Comment by ekzhang** [comment]
This would require giving some kind of _lease_ with expiry to the client that allows them to reconnect to the exact same port. It's possible, but that would add significant complexity to `bore`, which goes against the goals of the project.

**Comment by ekzhang** [comment]
(Though if you would like to add this to your own project or fork of bore, absolutely! Happy to help answer any questions about how such a system could be implemented.)
