### ISSUE TITLE
Is --port parameter respected?

### ISSUE THREAD

**Issue by vors** [ekzhang/bore#96]
Thank you for the awesome tool!

I'm running like this
```
./target/debug/bore local 8888 --port 443 --to foo.bar
```

Getting error
```
Error: could not connect to foo.bar:7835

Caused by:
    timed out
```

I didn't read the code in detail so maybe the error is only in the UI?

What I'd expect:
```
Error: could not connect to foo.bar:443
```

**Comment by ekzhang** [comment]
The `--port` parameter is the port you want to proxy 8888 to. You still need to open the control port, 7835.

**Comment by ekzhang** [comment]
See #48 — sorry 🙃 feel free to fork though, bore is minimal because it's meant to be easy to understand
