### ISSUE TITLE
Is bore down ? Getting OS error 61

### ISSUE THREAD

**Issue by sameeerkashyap** [ekzhang/bore#97]
Trying to run a bore server which was working fine all these days but suddenly getting this error 

```
 bore local 3001 --to bore.pub             
Error: could not connect to bore.pub:7835

Caused by:
    Connection refused (os error 61)
 ```
 
 Does this indicate a problem with the `bore.pub`

**Comment by ekzhang** [comment]
Thanks! Wow, I can't believe it's been up for over a year with no issues. Let me take a look.

**Comment by ekzhang** [comment]
Haha, looks like it failed because there were "too many open files" — I never changed my `ulimit -n` from its default of 1024.

```
bore bore[848766]: Error: Too many open files (os error 24)
```

Just fixed, should be back up again:

```text
$ bore local 3000 --to bore.pub
2023-10-03T23:20:22.084775Z  INFO bore_cli::client: connected to server remote_port=34185
2023-10-03T23:20:22.084844Z  INFO bore_cli::client: listening at bore.pub:34185
```

Still can't believe it's been running for a year with zero downtime until now, on a $6/month VM

**Comment by captn3m0** [comment]
seems down again:

```
bore local 4000 --to bore.pub
Error: could not connect to bore.pub:7835

Caused by:
    Connection refused (os error 111)
```

**Comment by danawoodman** [comment]
I got the same error when running NextDNS, disabling NextDNS allows it to work, leaving here for anyone else who comes across the issue.
